// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISSjNFmgneqL0u4zXv_KbayFDWTA9tY0',
    appId: '1:902053898129:web:2c060eeb1cb8f782511c30',
    messagingSenderId: '902053898129',
    projectId: 'agoraflutter-eba9d',
    authDomain: 'agoraflutter-eba9d.firebaseapp.com',
    storageBucket: 'agoraflutter-eba9d.firebasestorage.app',
    measurementId: 'G-5098L208J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFB0lWEVZkz20E6Bcg7EfAbUdsWDu3OLg',
    appId: '1:902053898129:android:6eeee3869b608ee9511c30',
    messagingSenderId: '902053898129',
    projectId: 'agoraflutter-eba9d',
    storageBucket: 'agoraflutter-eba9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt36WIxTMQkvi5AwyrvEctrwFKAnoucNU',
    appId: '1:902053898129:ios:fe000253e8d04639511c30',
    messagingSenderId: '902053898129',
    projectId: 'agoraflutter-eba9d',
    storageBucket: 'agoraflutter-eba9d.firebasestorage.app',
    iosBundleId: 'com.example.agoraVideoFriendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt36WIxTMQkvi5AwyrvEctrwFKAnoucNU',
    appId: '1:902053898129:ios:fe000253e8d04639511c30',
    messagingSenderId: '902053898129',
    projectId: 'agoraflutter-eba9d',
    storageBucket: 'agoraflutter-eba9d.firebasestorage.app',
    iosBundleId: 'com.example.agoraVideoFriendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCISSjNFmgneqL0u4zXv_KbayFDWTA9tY0',
    appId: '1:902053898129:web:30b12415cd058a74511c30',
    messagingSenderId: '902053898129',
    projectId: 'agoraflutter-eba9d',
    authDomain: 'agoraflutter-eba9d.firebaseapp.com',
    storageBucket: 'agoraflutter-eba9d.firebasestorage.app',
    measurementId: 'G-DWB61Y6QZC',
  );
}
